name: Build Automation - ${{ github.event.inputs.preset }}
on:
  workflow_dispatch:
    inputs:
      preset:
        type: choice
        required: true
        description: Preset for Builds
        options: 
        - BA_BuildPreset_1
        - BA_BuildPreset_2

jobs:
  building:
    name: Building game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Restore Library
        uses: actions/cache@v3
        with:
          path: Library/
          key: Library-Cache

      - name: Remove Cache
        run: |
          if [ -d "Builds" ]; then
            rm -rf ./Builds/*
          else
            mkdir ./Builds
          fi
      
      - name: Set CustomImage and Unity Version
        id: set-custom-image
        run: |
          preset="${{ github.event.inputs.preset }}"
          presets_json="./.github/workflows/preset.json"
          customImage=$(jq -r --arg preset "$preset" '.[$preset].customImage' "$presets_json")
          unityVersion=$(jq -r --arg preset "$preset" '.[$preset].unityVersion' "$presets_json")
          echo "Using customImage: $customImage"
          echo "Using unityVersion: $unityVersion"
          echo "::set-output name=customImage::$customImage"
          echo "::set-output name=unityVersion::$unityVersion"
        shell: bash

      - name: Building
        continue-on-error: true
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ steps.set-custom-image.outputs.unityVersion }}
          customImage: ${{ steps.set-custom-image.outputs.customImage }}
          buildMethod: BuildAutomation.BuildHelper.PerformBuild
          customParameters: -buildPreset ${{ github.event.inputs.preset }} -otherThing TestThing

      #check after builds
      - run: ls
      - run: ls Builds/
      - run: ls Assets/
        
      - name: Export
        uses: actions/upload-artifact@v3
        with:
          name: Build-Result
          path: Builds/*