name: UnityBuild-Import
on:
  workflow_dispatch:
    inputs:
      preset:
        type: choice
        required: true
        description: Preset for Builds
        options: 
        - BA_BuildPreset_1
        - BA_BuildPreset_2

jobs:
  building:
    name: Building game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Restore Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Cache

      - name: Remove Cache
        run: (if [ -d "Builds" ]; then rm -rf ./Builds/*; else mkdir ./Builds; fi);
      
      - name: Building
        continue-on-error: true
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.3f1
          customImage: 'unityci/editor:ubuntu-2022.3.3f1-android-3.0.0'
          buildMethod: BuildAutomation.BuildHelper.PerformBuild
          customParameters: -buildPreset ${{ github.event.inputs.preset }} -otherThing TestThing

      #check after builds
      - run: ls
      - run: ls Builds/
        
      - name: Export
        uses: actions/upload-artifact@v3
        with:
          name: Build-Result
          path: Builds/*